; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:adafruit_m4_express]
platform = atmelsam
board = adafruit_feather_m4
framework = arduino
lib_deps = 
    teemuatlut/TMCStepper@^0.7.3
    waspinator/AccelStepper@^1.64
build_src_filter = +<main.cpp>
build_flags = -O2

[env:huzzah32]
platform = espressif32
board = esp32dev
framework = arduino
board_build.filesystem = littlefs
lib_deps = 
    teemuatlut/TMCStepper@^0.7.3
    waspinator/AccelStepper@^1.64
    bblanchon/ArduinoJson@^7.4.2
    me-no-dev/AsyncTCP @ ^1.1.1
    https://github.com/me-no-dev/ESPAsyncWebServer.git
build_src_filter = +<web_host.cpp>
monitor_speed = 115200
build_flags = -O2
