git clone --recurse-submodules https://github.com/Moth-Balls/Hydro_Assist.git
fatal: destination path 'Hydro_Assist' already exists and is not an empty directory.
isaac@Michael Projects % rm -rf Hydro_Assist 
isaac@Michael Projects % git clone --recurse-submodules https://github.com/Moth-Balls/Hydro_Assist.git
Cloning into 'Hydro_Assist'...
remote: Enumerating objects: 210, done.
remote: Counting objects: 100% (210/210), done.
remote: Compressing objects: 100% (137/137), done.
remote: Total 210 (delta 94), reused 149 (delta 49), pack-reused 0 (from 0)
Receiving objects: 100% (210/210), 3.52 MiB | 13.36 MiB/s, done.
Resolving deltas: 100% (94/94), done.
Submodule 'Website' (https://github.com/bballew7/Website.git) registered for path 'Website'
Cloning into '/Users/isaac/Projects/Hydro_Assist/Website'...
remote: Enumerating objects: 12, done.        
remote: Counting objects: 100% (12/12), done.        
remote: Compressing objects: 100% (11/11), done.        
remote: Total 12 (delta 1), reused 12 (delta 1), pack-reused 0 (from 0)        
Receiving objects: 100% (12/12), 3.41 MiB | 6.69 MiB/s, done.
Resolving deltas: 100% (1/1), done.
fatal: remote error: upload-pack: not our ref de3f67ccf1ee58998dec80015a4d8311b8a137a8
fatal: Fetched in submodule path 'Website', but it did not contain de3f67ccf1ee58998dec80015a4d8311b8a137a8. Direct fetching of that commit failed.; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:adafruit_m4_express]
platform = atmelsam
board = adafruit_feather_m4
framework = arduino
lib_deps = 
    teemuatlut/TMCStepper@^0.7.3
    waspinator/AccelStepper@^1.64
build_src_filter = +<main.cpp>

[env:huzzah32]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps = 
    bblanchon/ArduinoJson@^7.4.2
    esp32async/AsyncTCP@^3.4.10
    me-no-dev/ESPAsyncWebServer@^1.2.3
build_src_filter = +<web_host.cpp>
